### ISSUE TITLE
Inferred properties optional

### ISSUE THREAD

**Issue by tstearn** [davidmdm/myzod#4] opened 2020-04-23 17:19 UTC
I noticed then I create a schema and then infer a type, that all the properties on the inferred type are optional:

  ```
export const userCreationSchema = myzod.object({
    userName: myzod.string(),
    displayName: myzod.string(),
    title: myzod.string().optional(),
    roleNames: myzod.array(myzod.enum(RoleName))
})
export type UserCreationDto = Infer<typeof userCreationSchema>;
```

So in this example, all the properties on UserCreationDto are optional.  Is this intentional?  Is there a way to make them required?

**Comment by tstearn** [comment] 2020-04-23 17:38
BTW, I don't mean they're optional from a validation perspective, but that the inferred type has all optional properties.

**Comment by davidmdm** [comment] 2020-04-23 18:33
@tstearn are you using vscode? I have experienced this issue with vscode at times too.

What you can do to test if this is actual an error in the type inference is do this:

```
const x: UserCreationDto = {};
```

This should not compile because the properties are missing and typescript will not build and will output the expected type. If they are all intilisensed as optional that is a vscode/typescript integration bug. If it does compile than there is something wrong and I will investigate ASAP

**Comment by davidmdm** [comment] 2020-04-23 19:11
@tstearn I investigated and was able to reproduce... It's a tsconfig issue.
Typescript views the type is conditional if you do not have strictNullChecks: `true`.

I will try and delve into seeing if this is a limitation of my type declarations but I think it might just be how typescript works. 

In the meanwhile I will close this issue. Thanks for reporting it, and I will write back if I find a way of making it work without strictNullChecks.

**Closed as completed** 2020-04-23 19:12 UTC

**Comment by davidmdm** [comment] 2020-04-23 19:31
@tstearn 

It's because typescript consideres everything to be a subtype of undefined if you do not activate structNullChecks.

How myzod infers if a property is conditional if if the infered value extends undefined.

So a schema like your evaluates normally to:
```
{
  userName: string;
  displayName: string;
  title: string | undefined;
  roleNames: RoleName[];
}
```
And only string | undefined extends undefined.

without strictNullChecks every type T extends undefined. and all properties get inferred as optional.
 you can read about it here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

Would this affect your adoption of myzod? In general I think it is good practice to have strictNullChecks on. 

I may experiment with a different approach though in order to infer which properties are optional, and possibly support strictNullChecks: `false`

In the meantime does this answer your issue?

**Comment by mscottnelson** [comment] 2020-04-23 20:41
just my two cents, but `strictNullChecks: true` fits the spirit of the validation, and having optional params represents reality about what TypeScript has actually checked. "It's a feature" that the validator returns optional types when strictNullChecks are disabled...although I suppose in a world of `strictNullChecks: false` there is a real benefit in having assurance that the *key* is there even if its value is undefined. ...that too may be false, though, because of the way `delete key` does not happen immediately but instead sets the value to undefined until the next garbage collection.

**Comment by davidmdm** [comment] 2020-04-23 21:46
@mscottnelson , I tend to agree with you on principle. As I also don't think you should be using typescript without strict null checks activated. However technically the validation will ensure that the key is there if its schema is non-optional... So if I can make it work without strictNullChecks, I think it is worth doing in theory although in practice it may prove to not be the case. 

I've started exploring the possibility. It's actually more work than I bargained for and I may need to change the way I represent union types... We shall see.

What I would like to know is if this is a blocker for you @tstearn ?
